version: '3'

services: 

  myapp-mongodb:
    
    image: mongo:3.2.4
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles

  myapp-main:
    build : .
    
    restart: always
    depends_on:
      - myapp-mongodb
    ports:
      - 8080:8080
       